### ISSUE TITLE
Cannot sign in

### ISSUE THREAD

**Issue by jackynguyen93** [J-Rios/TLG_export_chat_data#1]
I try to sign in but got this error:

 python3 tlg_exportdata.py 

Traceback (most recent call last):
  File "tlg_exportdata.py", line 259, in <module>
    main()
  File "tlg_exportdata.py", line 224, in main
    client.sign_in(PHONE_NUM,  LOGIN_CODE)
  File "/home/nguyenvan/.local/lib/python3.5/site-packages/telethon/telegram_client.py", line 393, in sign_in
    raise ValueError('You also need to provide a phone_code_hash.')
ValueError: You also need to provide a phone_code_hash.

**Comment by J-Rios** [comment]
That happens when your LOGIN_CODE does not match with the one expected by Telegram service. 

When you execute "firstrun.py" file, a message with the LOGIN_CODE is sent to your telegram account and then, telegram is allowing a login using that code, so in that moment you have to set that LOGIN_CODE in "tlg_exportdata.py" and run it for login. The result of the client auth and login is stored in a "Session.session" file, so next times that you want to execute the script it does not require the login (so you just need to execute the firstrun.py script once).

Just try to remove the "Session.session" file and follow the "How to use" section of the README file again...

**Comment by jackynguyen93** [comment]
Thanks for your answer, one more about user info, can we get join date or leave date or invited method of user ???

**Comment by J-Rios** [comment]
Well, this script is just an example of using Python Telethon library to access the Telegram client API and export some basic information to JSON files, sure you can get other information that the API can provide, but modifying the script or writing a new one.

- About user join date: sure you can obtain that field directly by reading participants data.

- About user left date: the script get the actual users in the chat, not the data of all the users that has been in the group/channel at some point. Don't know if telegram API provide such info about a chat directly, however, i think that one way to get that info is by looking through each message, determine "left-group" messages and check that messages info to get users and left dates.

- About "join/invite mode": Does not seems that there is directly info about it. Maybe you can obtain that by getting each message data, determine "join-group" messages and check that messages info.


Telethon library:
https://github.com/LonamiWebs/Telethon

Telethon library documentation:
http://telethon.readthedocs.io/en/latest/

Telegram client API documentation:
https://core.telegram.org/#telegram-api


Pull requests to the script are welcome :)

**Comment by jackynguyen93** [comment]
That is what I am researching. Howerver, I can not get join date in participant data, just  username, lastname, firstname, online status are provided. 
I also think about get message "XXX join channel" or "XXX leave the channel", but it seems we cannot get that message.
The finnal solution I can do is creating a bot to check the event join or leave, then store it to database. But with the existing user, it is not possible to get the join date :( 
Do you have any better idea???

**Comment by J-Rios** [comment]
I have modified the script, change some things and added some others, like added a way to get join date for users and export that info in the users json file.

So, you can get user join date by using "GetParticipantsRequest()". For left channel/group, seems that the only way is through the "XXX leave the group/channel" messages (not sure if there is other way); this messages can be obtained like any other, but only if the group/channel allow them (if they are shown in the chat), i think that if the group is too small or too big, they are not showing up, and cannot be obtained.

No idea ¯\\_(ツ)_/¯

**Comment by jackynguyen93** [comment]
Thanks for your help. btw, your new commit is missing the import GetFullChannelRequest
Again, thank you so much ^^

**Comment by J-Rios** [comment]
OMG, fixed xD

**Comment by jackynguyen93** [comment]
Hello, is this only work with channel ? how about group ?

**Comment by J-Rios** [comment]
It also works with groups, but just for the ones that are publics (have an alias and link), otherwise you need to join the client to that group before run the script.

About channels, it is necessary that the client has Admin privileges in that channel to use some functions needed to search participants...

**Comment by jackynguyen93** [comment]
gotcha, and one more thing, can we get the list of banned user of a channel ?

I see api has this one: https://core.telegram.org/method/contacts.getBlocked

**Comment by J-Rios** [comment]
Sure, but not implemented in the script.

Of course, the client also need to be an Admin of the channel to get that info.

**Comment by jackynguyen93** [comment]
Could you help me to point out what api in telethon libary that we can use to get list banned users. I tried but didnt find it :(

**Comment by J-Rios** [comment]
I am a novice in Telegram client API and Telethon, just did this 2 scripts (TLG_export_chat_data and TLG_export_chat), no more, so don't know how to do nothing different than the things I do it in that scripts until I go into code some new feature...


What it seems to me is:

- There is no a basic function in telethon to get banned users of a channel, but looking in the documentation of Telethon, it said that there is a method to get access to full Telegram API functions (see http://telethon.readthedocs.io/en/latest/extra/advanced-usage/accessing-the-full-api.html)

- I see an API request called "ChannelParticipantsBanned" (https://lonamiwebs.github.io/Telethon/constructors/channel_participants_banned.html).

So, i think that you have to follow the "Access full API" instructions and try to figure out the way to get the corresponding Telethon call to the ChannelParticipantsBanned API request...


P.D. Maybe you should open an issue in Telethon repo, asking for some guideance of how to get that channel info: https://github.com/LonamiWebs/Telethon/issues

**Comment by jackynguyen93** [comment]
Cool, that is exactly what I need. Thank you so much.
I think we can replace filter=ChannelParticipantsSearch('') by ChannelParticipantsBanned to filter banned user.

**Comment by J-Rios** [comment]
New version ([e23ed9c](https://github.com/J-Rios/TLG_export_chat_data/commit/e23ed9cc2e71c6b2a407d1276c2016084c118853)) that simplify the sign in process using just the main script (firstrun script removed).

See how to use this new script version in Readme file.
