### ISSUE TITLE
Can not log in

### ISSUE THREAD

**Issue by Stepkaa** [J-Rios/TLG_export_chat_data#2]
Hi! Thanks for your work! I've read everything (including previous issue and done all steps according to readme). Still getting this error. 

I have the latest version of Telethon. What can be the issue here?

Code is not modified in any way, telegram account is new, I am getting the login code in the app.

`Traceback (most recent call last):
  File "tlg_exportdata.py", line 311, in <module>
    main()
  File "tlg_exportdata.py", line 276, in main
    client.sign_in(PHONE_NUM, LOGIN_CODE)
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_client.py", line 420, in sign_in
    raise ValueError('You also need to provide a phone_code_hash.')
ValueError: You also need to provide a phone_code_hash.`

**Comment by J-Rios** [comment]
Duplicated Issue - #1 

New version ([e23ed9c](https://github.com/J-Rios/TLG_export_chat_data/commit/e23ed9cc2e71c6b2a407d1276c2016084c118853)) that simplify the sign in process using just the main script (firstrun script removed).

See how to use now in Readme file.
